FROM postgres:latest

# Environment variables
# Once again set else where for deployed version
# Do not bother trying lol
ENV POSTGRES_USER="postgres"
ENV POSTGRES_PASSWORD="postgres"
ENV POSTGRES_DATABASE="postgres"
